### ISSUE TITLE
filename issue

### ISSUE THREAD

**Issue by Kuuuo** [Tony607/voc2coco#8]
Number of xml files: 3000
Traceback (most recent call last):
  File "E:/voc2coco-master/voc2coco.py", line 157, in <module>
    convert(xml_files, json_file)
  File "E:/voc2coco-master/voc2coco.py", line 83, in convert
    filename = get_and_check(root, "filename", 1).text
  File "E:/voc2coco-master/voc2coco.py", line 29, in get_and_check
    raise ValueError("Can not find %s in %s." % (name, root.tag))
ValueError: Can not find filename in annotation.

**Comment by Millielele** [comment]
> Number of xml files: 3000 Traceback (most recent call last): File "E:/voc2coco-master/voc2coco.py", line 157, in convert(xml_files, json_file) File "E:/voc2coco-master/voc2coco.py", line 83, in convert filename = get_and_check(root, "filename", 1).text File "E:/voc2coco-master/voc2coco.py", line 29, in get_and_check raise ValueError("Can not find %s in %s." % (name, root.tag)) ValueError: Can not find filename in annotation.

Do you solve this issue?
